### ISSUE TITLE
would it be difficult to merge these features with NCBITaxonomy?

### ISSUE THREAD

**Issue by gottacatchenall** [banhbio/Taxonomy.jl#5]
Hi there, 

I'm interested in knowing how this feature-set varies with [NCBITaxonomy.jl](https://github.com/EcoJulia/NCBITaxonomy.jl). Could the two be integrated at some point? We are also considering a taxonomy package that can handle arbitrary rank systems

**Comment by banhbio** [comment]
Sorry for the late reply due to my stupid email settings.

I'm developing this package to make it easier to handle linage information (using rank systems, of course). There may be some point where we can merge them, but this package is still in the development stage and needs to mature a bit more.

**Comment by banhbio** [comment]
close issue
